# env → catalog/schema (unchanged structure)
#prd:
  #catalog_name: mlops_prd
  #schema_name: hotel_reservations
#acc:
  #catalog_name: mlops_acc
  #schema_name: hotel_reservations
dev:
  catalog_name: mlops_dev
  schema_name: prakashs


# model params (optional defaults)
parameters:
  learning_rate: 0.01
  n_estimators: 300
  max_depth: 6

# === HOTEL FEATURES ===
num_features:
  - no_of_adults
  - no_of_children
  - no_of_weekend_nights
  - no_of_week_nights
  - required_car_parking_space
  - lead_time
  - arrival_year
  - arrival_month
  - arrival_date
  - no_of_previous_cancellations
  - no_of_previous_bookings_not_canceled
  - avg_price_per_room
  - no_of_special_requests

cat_features:
  - type_of_meal_plan
  - room_type_reserved
  - market_segment_type
  - repeated_guest

target: booking_status
